In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
!ls log_files2

'fitness_&_operator_probs_geno_log.csv'    results_geno_log.csv
'fitness_&_operator_probs_GP_log.csv'	   results_GSGP_log.csv
'fitness_&_operator_probs_naive_log.csv'   results_naive_log.csv
'fitness_&_operator_probs_pheno_log.csv'   results_operators_log.csv
 programs_GP_log.csv			   results_pheno_log.csv
 results_algos_log.csv

In [6]:
df = pd.read_csv('log_files2/results_operators_log.csv') 
df.head()

,Seed,Algorithm,time,mean_s_error,explained_variance,final_tree_size
0,1,GP_normal_fitness,0:00:14.295953,2.099398,-1.664867,NaN
1,0,GP_fitness,0:00:15.808751,1.799009,-1.213527,NaN
2,0,GP_no_operator,0:00:19.240520,1.926161,-0.506444,NaN
3,0,GP_tournament,0:00:19.595506,1.926161,-0.506444,NaN
4,0,GP_pheno_operator,0:00:19.664632,1.926161,-0.506444,NaN

In [15]:
df[df['Algorithm'].isin(['GP_rank','GP_roulette','GP_fitness','GP_no_operator'])].groupby('Algorithm').describe().T

Algorithm                 GP_fitness  GP_no_operator    GP_rank  GP_roulette
Seed               count    5.000000        5.000000   5.000000     5.000000
                   mean     2.000000        2.000000   2.000000     2.000000
                   std      1.581139        1.581139   1.581139     1.581139
                   min      0.000000        0.000000   0.000000     0.000000
                   25%      1.000000        1.000000   1.000000     1.000000
                   50%      2.000000        2.000000   2.000000     2.000000
                   75%      3.000000        3.000000   3.000000     3.000000
                   max      4.000000        4.000000   4.000000     4.000000
explained_variance count    5.000000        5.000000   5.000000     5.000000
                   mean    -2.475681       -3.726917  -0.842442   -13.988193
                   std      2.742467        3.665343   1.184055    14.430276
                   min     -7.358680       -8.056812  -2.473491   -32.425292
                   25%     -1.664867       -7.358680  -1.742244   -26.703568
                   50%     -1.215983       -1.664867  -0.036346    -5.842597
                   75%     -1.213527       -1.047780   0.000000    -2.881703
                   max     -0.925349       -0.506444   0.039872    -2.087804
final_tree_size    count    0.000000        0.000000   0.000000     0.000000
                   mean          NaN             NaN        NaN          NaN
                   std           NaN             NaN        NaN          NaN
                   min           NaN             NaN        NaN          NaN
                   25%           NaN             NaN        NaN          NaN
                   50%           NaN             NaN        NaN          NaN
                   75%           NaN             NaN        NaN          NaN
                   max           NaN             NaN        NaN          NaN
mean_s_error       count    5.000000        5.000000   5.000000     5.000000
                   mean     2.550960        2.317282   7.332073     2.395144
                   std      0.679893        0.332064   3.982090     0.469895
                   min      1.799009        1.926161   3.260590     2.009767
                   25%      2.099398        2.099398   4.192172     2.156095
                   50%      2.341908        2.286156   6.196240     2.281101
                   75%      3.118843        2.505507  10.848387     2.321732
                   max      3.395643        2.769190  12.162978     3.207025